export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CONTACT = "SET_CONTACT";
export const CLEAR_CONTACT = "CLEAR_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACT = "FILTER_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const CLEAR_FILTER = "CLEAR_FILTER";
